<a href="https://colab.research.google.com/github/pyc970905/pythonBigData/blob/main/%EB%B9%84%ED%8A%B82205_%EB%B6%84%EC%84%9D%EC%8B%9C%EA%B0%81%ED%99%94_02_numpy_%EB%9D%BC%EC%9D%B4%EB%B8%8C%EB%9F%AC%EB%A6%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
import numpy as np
# numpy를 쓰면 메모리를 사용량과 속도가 빠르다.

ls3 = [[1,2,3],[2,3],[4,5,6,7]]
#arr3= np.array(ls3)            numpyd의 배열은 원소 형식이 같아야 한다.
arr3 = np.array([[1,2],[3,4],[5,6]])

In [29]:
print(arr3)

[[1 2]
 [3 4]
 [5 6]]


In [30]:
ls4 = list(range(10))
arr4 = np.arange(10)
print(arr4)

#arr = []
#for i in range(100):
# arr4.append(i)
# 보다 효율이 좋은 형식이다.

[0 1 2 3 4 5 6 7 8 9]


In [31]:
ls5 = ls4*2     #리스트 요소의 값을 하나하나 2로 나눠주는 구문이아니다.
arr5 = arr4*2   #numpy를 통해 수학적 연산이 가능한 리스트로 변환을 해주어야한다.
print(ls5)
print('------')
print(arr5)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
------
[ 0  2  4  6  8 10 12 14 16 18]


In [32]:
arr = np.array([1,2,3])
arr.shape

(3,)

In [33]:
arr2 = np.array([[1,2,3],[1,2,3]])
arr2.shape

(2, 3)

In [34]:
arr3= np.random.randn(2,3)
print(arr3.shape)
print(arr3)

(2, 3)
[[ 0.91984314 -0.84518144 -0.54183833]
 [-1.10555194 -1.5033858   1.44805632]]


In [35]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,2],[1,3]])
arr3 = arr1 + arr2
print(arr3)

[[6 4]
 [4 7]]


In [36]:
arr = np.array([1,2,'a',3.23])
arr.dtype

dtype('<U32')

In [37]:
arr = np.array([1,2,3])
arr.dtype

dtype('int64')

In [38]:
arr = np.array([1,2,3,4.0])
arr.dtype

for i in range(4):
  print(arr[i])

1.0
2.0
3.0
4.0


In [39]:
arr = np.array([1,'a',2.3])
print(type(arr[0]),type(arr[1]),type(arr[2]))
arr.dtype                                     #각 요소의 데이터 타입이 다르다면 요소중 가장 많은 데이터를 차지하는 요소의 데이터 타입으로 통일해준다.

<class 'numpy.str_'> <class 'numpy.str_'> <class 'numpy.str_'>


dtype('<U32')

#배열 생성

In [40]:
arr = np.array([1,2,3]) # 리스트를 입력 인자로 배열 개체 생성
print(arr)

[1 2 3]


In [41]:
arr2 =np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [42]:
print("차원:",arr2.ndim)
print("구조:",arr2.shape)

차원: 2
구조: (2, 3)


In [43]:
arr3 = np.zeros(10) #0을 원소로 하는 배열
print(arr3)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [44]:
arr4 = np.zeros((4,5))   #0을 원소로 4*5 구조의 배열 생성
print(arr4)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [45]:
arr5 = np.ones(10) # 모든 원소를 10으로 채운다.

In [46]:
arr6 = np.ones((2,3))
print(arr6)

[[1. 1. 1.]
 [1. 1. 1.]]


In [47]:
arr7 = np.arange(5,100,3)
print(arr7)

[ 5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50 53 56 59 62 65 68 71 74
 77 80 83 86 89 92 95 98]


# 원소 타입

In [48]:
arr = np.array([1,2,3])
print(arr.dtype)

int64


In [49]:
arr2 = np.array([12,3.4,3])
print(arr2.dtype)

float64


In [50]:
arr3 = np.array([1,2,3,4],dtype=np.float64)
print(arr3.dtype)

float64


In [51]:
print(arr3)
arr4 = arr3.astype(int)
print(arr4)

[1. 2. 3. 4.]
[1 2 3 4]


In [52]:
arr1= np.array([[1,2,3],[3,4,5]])
arr2 = np.array([[2,1,0],[1,2,3]])
print("arr1\n",arr1)
print("arr2\n",arr2)

arr1
 [[1 2 3]
 [3 4 5]]
arr2
 [[2 1 0]
 [1 2 3]]


In [53]:
arr3 = arr1 + arr2
print("arr1-arr2\n",arr3)

arr1-arr2
 [[3 3 3]
 [4 6 8]]


In [54]:
arr5 = arr1 * arr2
print("arr1*arr2\n",arr5)

arr1*arr2
 [[ 2  2  0]
 [ 3  8 15]]


In [55]:
arr6 = np.dot(arr1,arr2)
print(arr6)  #행렬 내적의 오류

ValueError: ignored

In [56]:
arr7 = arr1/3.0
print("arr1/3,0\n",arr7)

arr1/3,0
 [[0.33333333 0.66666667 1.        ]
 [1.         1.33333333 1.66666667]]


In [57]:
arr8 = arr1*3.0
print("arr1*3,0\n",arr8)

arr1*3,0
 [[ 3.  6.  9.]
 [ 9. 12. 15.]]


#간단한 활용 예

In [ ]:
heights = np.random.normal(172.5,scale=5,size=1000)
print(sum(heights)/len(heights))

In [ ]:
import matplotlib.pyplot as plt

plt.plot(heights,'.')
plt.show()


In [ ]:
bins  = np.zeros(50)
for height in heights :
  index = int(height)-150
  bins[index] = bins[index]+1
print(bins)

In [ ]:
plt.plot(bins,'.')
plt.show()

In [ ]:
bmis = np.random.normal(22,scale=2,size=1000)
print(sum(bmis)/len(bmis))

In [ ]:
bins  = np.zeros(200)
for bmi in bmis :
  index = int(bmi*10)-120
  
  bins[index] = bins[index]+1
plt.plot(bins,'.')
plt.show()

In [ ]:
weights = bmi * heights*heights/10000
print(sum(weights)/len(weights))

In [ ]:
std_heights = np.std(heights)
aver_heights = np.average(heights)
print("표준 편차:",std_heights)
print("평균 :",aver_heights)

In [ ]:
heights2 = (heights-aver_heights)/std_heights
std_heights2 = np.std(heights2)
aver_heights2 = np.average(heights2)
print("표준 편차:",std_heights2)
print("평균 :",aver_heights2)

#슬라이스

In [ ]:
arr = np.arange(1000)
print(arr)

In [ ]:
arr[5:8]

In [ ]:
arr[-2]

In [ ]:
arr[980:-1]

In [ ]:
arr[:5]

In [ ]:
arr[980:]

In [ ]:
arr[::3]

In [ ]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2[0])

In [ ]:
arr2[0][1]

In [ ]:
type(arr2)

In [ ]:
arr2[:][1]

# 필터 선택


In [ ]:
arr = np.array([1,3,2,5,4,7,8])
print(arr)

In [ ]:
filter = arr%2 ==0
print(filter)

In [ ]:
even_arr = arr[filter]
even_arr

#구조 변경

In [ ]:
arr = np.arange(7*2*5)
print(arr)

In [ ]:
print(arr.shape)

In [ ]:
arr2 = arr.reshape((7,-1))

In [ ]:
print(arr2)

In [ ]:
arr3 = arr.reshape(7,-1,5) # -1은 자동으로 계산해서 원소 갯수를 나눠준다.
print(arr3.shape)
print(arr3)

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
arr2 = arr.T
print(arr2)

In [ ]:
arr3 = arr.transpose()
print(arr3)

#자잘한 함수

In [ ]:
arr = np.random.randint(0,100,5)
print(arr)

In [ ]:
arr2 = np.sqrt(arr)
print(arr2)

In [ ]:
arr3 = np.random.randint(0,100,5)
print(arr3)

In [ ]:
arr4 = np.maximum(arr,arr3)
print(arr4)

# numpy 활용 예 -영상처리

In [ ]:
import cv2 #OpenCV 라이브러리
from google.colab.patches import cv2_imshow #코랩에서 시각화를 위해 필요한 구문

In [ ]:
path = '/content/drive/MyDrive/PHOTO_0905.jpg'
image = cv2.imread(path,cv2.IMREAD_COLOR)
cv2_imshow(image)

In [ ]:
print(type(image))

In [ ]:
print(image.ndim)

In [ ]:
print(image.shape)

In [ ]:
image[:,:,0] =255
cv2_imshow(image)

In [ ]:
image[:,:,2]=255
cv2_imshow(image)

In [ ]:
from tensorflow import keras

In [ ]:
data = keras.datasets.mnist.load_data()

In [ ]:
print(type(data))

In [ ]:
print(len(data))

In [ ]:
train_data,test_data=data
print(type(train_data))
print(len(train_data))
print(type(test_data))
print(len(test_data))


In [ ]:
x_train,y_train = train_data
x_test,y_test = test_data
print(type(x_train),type(y_train))
print(type(x_test),type(y_test))

In [ ]:
print(x_train.shape, y_train.shape)
print(x_test.shape, y_test.shape)

In [ ]:
for i in range(10):
  image = x_train[i]
  print(y_train[i])
  cv2_imshow(image)

In [163]:
arr = np.random.randint(5,100,20)
print(arr)

[76 35 84 45 76  9 94 50 92 55 20 11 91 70 94 76 36 39 27 13]


In [164]:
arr2 = arr.reshape(4,-1)
print(arr2)

[[76 35 84 45 76]
 [ 9 94 50 92 55]
 [20 11 91 70 94]
 [76 36 39 27 13]]


In [165]:
print('평균:',arr2.mean())

평균: 54.65


In [86]:
print('평균(축1):',arr2.mean(axis=1)) #칼럼 축
print('평균(축2):',arr2.mean(axis=0)) #로우 축

평균(축1): [65.6 56.  70.6 46.6]
평균(축2): [70.75 62.25 62.5  55.   48.  ]


In [87]:
print('합계:',arr2.sum()) #칼럼 축
print('평균(축1):',arr2.mean(axis=1)) #칼럼 축
print('평균(축0):',arr2.mean(axis=0)) #로우 축

합계: 1194
평균(축1): [65.6 56.  70.6 46.6]
평균(축0): [70.75 62.25 62.5  55.   48.  ]


In [166]:
print('표준편차:',arr2.std()) #칼럼 축
print('분산:',arr2.var()) #칼럼 축
print('최솟값:',arr2.min()) #로우 축
print('최댓값:',arr2.max()) #로우 축

표준편차: 29.20663452025926
분산: 853.0274999999999
최솟값: 9
최댓값: 94


In [167]:
arr=np.array([1,3,2,4,56,5,-2,3])
print("최댓값인덱스:",arr.argmax())
print('최솟값인덱스:',arr.argmin())

최댓값인덱스: 4
최솟값인덱스: 6


In [168]:
arr = np.array([1,2,3,2,4,5])
cs = arr.cumsum()
print(cs)

[ 1  3  6  8 12 17]


In [12]:
import numpy as np


In [3]:
def subtract(ls1,ls2):
  assert len(ls1)==len(ls2), "두개의 리스트 원소 개수는 같아야 합니다."
  return [ls1[i]-ls2[i] for i in range(len(ls1))]

In [5]:
assert subtract([4,2,8],[1,3,5])== [3,-1,3]

In [6]:
def scalar_multiply(ls1,num):
  return[num*ls1[i] for i in range(len(ls1))]

In [7]:
assert scalar_multiply([2,3,4],3)==[6,9,12]

In [8]:
arr1= [[1,2],[3,4]]
arr2 = [[2,3],[1,2]]
re = np.dot(arr1,arr2)
print(re)

NameError: ignored

In [13]:
arr = np.diag((3,3,1,3,5,7))
print(arr)

[[3 0 0 0 0 0]
 [0 3 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 3 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 7]]


In [15]:
for _ in range(10):
  print(np.random.rand()) # 0,1사이의 랜덤한 실수

0.7099169653463194
0.8715867188992803
0.8752883739474866
0.5011234424765852
0.8648169678178229
0.7382522503766198
0.7203729363924444
0.09144630439527013
0.32956088827468566
0.8995695450563993


In [17]:
for _ in range(10):
  print(np.random.random(size=3)) #0,1 사이의 랜덤한 실수를 3개씩 하나의 리스트로 

[0.78463964 0.51354881 0.5462654 ]
[0.25763443 0.77895071 0.54223821]
[0.82185307 0.75201415 0.26903204]
[0.55862546 0.0204566  0.13067597]
[0.22801115 0.70221223 0.58031386]
[0.90045532 0.3190805  0.37474874]
[0.41340175 0.78399786 0.73272429]
[0.95317403 0.91063113 0.0306122 ]
[0.78709541 0.9767659  0.29351568]
[0.08566215 0.53823035 0.51137228]


In [20]:
for _ in range(10):
  print(np.random.uniform(-2.3)) #시작과 끝값을 설정해 그사이의 랜덤한 실수를 뽑아낸다.

0.6093932159828972
0.696713871498599
-1.235245834877259
-0.6180979407493519
0.0907719327266947
-2.2097154830389165
0.8703397706797236
-0.3415708842684535
-0.6669956926506089
-1.0482573885427893


In [22]:
for _ in range(10):
  print(np.random.randint(10)) #숫자하나를 주면 그값은 뽑힐수 있는 최댓값, 두개를 넣으면 그사이의 임의의 정수 반환

5
1
9
4
6
6
7
7
2
5


In [28]:
for _ in range(10):
  print(np.random.randint(1,6),end=' ')  # end값은 포함되지 않는다.

5 1 4 3 1 4 4 4 2 4 

In [29]:
for _ in range(10):
  print(np.random.choice([1,3,2,8]),end=' ')

2 2 1 3 3 8 2 2 2 8 